name: Compile WASM

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2


    - name: Set up Emscripten
      uses: mymindstorm/setup-emsdk@v14

    - name: Verify Emscripten
      run: emcc -v
        
    - name: Compile mt19937.c to mt.wasm
      run: |
        cd MT
        make

    - name: Upload mt.wasm artifact
      uses: actions/upload-artifact@v4
      with:
        name: mt-wasm
        path: MT/mt.wasm
